# Generated by Django 4.1 on 2022-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
